# Generated by Django 5.0.7 on 2024-07-23 17:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(help_text='Detailed down description of message - markdown and html langauge supported')),
                ('alert_type', models.CharField(choices=[('alert', 'Alert'), ('news', 'News'), ('information', 'Information')], default='alert', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
